# Generated by Django 3.1.3 on 2021-01-20 10:02

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AlterField(
            model_name='offer',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
