# Generated by Django 3.1.3 on 2021-01-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            ALTER TABLE "members_member" ADD COLUMN "textsearch" tsvector
            GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(name, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(email, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(phone, '')), 'A') ||
            ' '
            ) STORED NULL;
            CREATE INDEX textsearch_idx ON members_member USING GIN (textsearch);
        """, reverse_sql="""
            DROP INDEX IF EXISTS textsearch_idx;
            ALTER TABLE "members_member" DROP COLUMN "textsearch";
        """
        )
    ]
