# Generated by Django 3.1.3 on 2020-12-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_customuser_created_by'),
        ('user_panel', '0003_customuser_organization'),
    ]

    operations = [
    ]
