# Generated by Django 3.1.3 on 2021-01-11 13:06

from django.db import migrations, models
from django.conf import settings

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=settings.MERCHANT_ADMIN)
    Group.objects.get_or_create(name=settings.MERCHANT_WORKER)


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            settings.MERCHANT_ADMIN,
            settings.MERCHANT_WORKER
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_merge_20201229_1232'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
