# Generated by Django 3.1.3 on 2021-02-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0003_auto_20210124_1553'),
        ('organizations', '0001_initial'),
        ('audience', '0002_auto_20210124_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('metadata', models.JSONField(default=dict)),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audience.audience')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
            ],
        ),
    ]
