# Generated by Django 3.1.3 on 2021-01-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20201213_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
