# Generated by Django 3.1.3 on 2021-02-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_orderline_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
