# Generated by Django 3.1.3 on 2021-02-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_delete_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderline', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipts.store'),
        ),
    ]
