# Generated by Django 3.1.3 on 2021-02-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_article_number'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            ALTER TABLE "receipts_article" ADD COLUMN "textsearch" tsvector
            GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
            ' '
            ) STORED NULL;
            CREATE INDEX article_textsearch_idx ON receipts_article USING GIN (textsearch);
        """, reverse_sql="""
            DROP INDEX IF EXISTS article_textsearch_idx;
            ALTER TABLE "receipts_article" DROP COLUMN "textsearch";
        """
        )
    ]
