# Generated by Django 3.1.3 on 2021-01-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audience',
            unique_together={('name', 'organization')},
        ),
    ]
