export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';

export const LIST_USERS = 'LIST_USERS';
export const DEACTIVATE_USER = 'DEACTIVATE_USER';
export const FULL_DELETE_USER = 'FULL_DELETE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const CHANGE_OWN_PASSWORD = 'CHANGE_OWN_PASSWORD';

export const LIST_STORES = 'LIST_STORES';
export const LIST_ARTICLES = 'LIST_ARTICLES';
export const TRENDING_ARTICLES = 'TRENDING_ARTICLES';
export const RECOMMENDED_ARTICLES = 'RECOMMENDED_ARTICLES';
export const CONNECTED_ARTICLES = 'CONNECTED_ARTICLES';

export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const CONNECTED_PRODUCTS = 'CONNECTED_PRODUCTS';
export const TRENDING_PRODUCTS = 'TRENDING_PRODUCTS';
export const RECOMMENDED_PRODUCTS = 'RECOMMENDED_PRODUCTS';

export const GET_METRICS = 'GET_METRICS';

export const LIST_CAMPAIGNS = 'LIST_CAMPAIGNS';
export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const DUPLICATE_CAMPAIGN = 'DUPLICATE_CAMPAIGN';

export const LIST_ORGS  = 'LIST_ORGS';
export const DELETE_ORG = 'DELETE_ORG';
export const UPDATE_ORG = 'UPDATE_ORG';
export const CREATE_ORG = 'CREATE_ORG';

export const LIST_OFFERS = 'LIST_OFFERS';
export const DELETE_OFFER = 'DELETE_OFFER';
export const UPDATE_OFFER = 'UPDATE_OFFER';
export const CREATE_OFFER = 'CREATE_OFFER';

export const LIST_AUDIENCE = 'LIST_AUDIENCE';
export const DELETE_AUDIENCE = 'DELETE_AUDIENCE';
export const UPDATE_AUDIENCE = 'UPDATE_AUDIENCE';
export const CREATE_AUDIENCE = 'CREATE_AUDIENCE';

export const LIST_MEMBERS = 'LIST_MEMBERS';
export const LIST_MEMBER_RECEIPTS = 'LIST_MEMBER_RECEIPTS';
export const LIST_MEMBER_CAMPAIGNS = 'LIST_MEMBER_CAMPAIGNS';
export const LIST_MEMBER_CAMPAIGN_ORDERS = 'LIST_MEMBER_CAMPAIGN_ORDERS';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const CREATE_MEMBER = 'CREATE_MEMBER';

export const LIST_RECEIPT_ORDERS = 'LIST_RECEIPT_ORDERS';
